env: TRAVIS_CI=true
language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  # for unit tests
  - sudo apt-get install -y check
  # for static code analysis
  - sudo apt-get install -y cppcheck rats
  # for test code coverage
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs cppcheck 2>&1
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs rats --language=c
  - git clone --depth 10 https://github.com/proftpd/proftpd.git
  - mkdir -p proftpd/contrib/mod_vroot/
  - cp *.[ch] proftpd/contrib/mod_vroot/
  - cp mod_vroot.* proftpd/contrib/mod_vroot/
  - cp Makefile.in proftpd/contrib/mod_vroot/
  - cp config* proftpd/contrib/mod_vroot/
  - cp install-sh proftpd/contrib/mod_vroot/
  - cp -R t/ proftpd/contrib/mod_vroot/t/
  - cd proftpd
  - ./configure LIBS='-lm -lrt -pthread' --enable-devel=coverage --enable-dso --enable-tests --with-shared=mod_vroot
  - make
  - make clean
  - ./configure LIBS='-lm -lrt -pthread' --enable-devel=coverage --enable-tests --with-modules=mod_vroot
  - make
  - cd contrib/mod_vroot && make TEST_VERBOSE=1 check && cd ../../
